# Generated by Django 2.2 on 2021-01-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiser',
            name='ads',
            field=models.ManyToManyField(to='advertiser_management.Ad'),
        ),
    ]
