# Generated by Django 2.2 on 2021-01-28 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0002_advertiser_ads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertiser',
            name='ads',
        ),
        migrations.AddField(
            model_name='ad',
            name='advertiserId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='advertiser_management.Advertiser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
