# Generated by Django 2.2 on 2021-01-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0003_auto_20210129_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='advertiserId',
            new_name='advertiser',
        ),
        migrations.AlterField(
            model_name='ad',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
