# Generated by Django 2.2 on 2021-01-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0006_auto_20210129_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='imgUrl',
        ),
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
