# Generated by Django 2.2.18 on 2021-02-03 11:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0007_auto_20210129_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='views',
        ),
        migrations.AddField(
            model_name='ad',
            name='approve',
            field=models.CharField(choices=[('a', 'APPROVED'), ('d', 'Disapproved'), ('n', 'Not checked')], default='n', max_length=1),
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 2, 3, 11, 52, 19, 539820, tzinfo=utc))),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertiser_management.Ad')),
            ],
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 2, 3, 11, 52, 19, 540128, tzinfo=utc))),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertiser_management.Ad')),
            ],
        ),
    ]
